### PR TITLE
Update the Map card's formatting

### PR DESCRIPTION
**Pull request by nachtm**
I made a lot of styling updates. The end result looks like this:
image

Compare to the comps:
image

Down the line we should probably fix the max bounds -- they're behaving a little weirdly at the moment. Happy to go explain more in-depth if needed.

### CODE REVIEW

**Comment by nachtm** [comment]
1. Unfortunately the style is stored by `<App/>` because it needs to be passed into the `<Map/>`; `<Map/>` needs to be high in the tree so we don't re-render it unnecessarily. I think getting this to switch back to None every time we load a new page is going to be more trouble than it's worth. If you feel strongly I'm happy to discuss.

2. The presence of a maximum bounds was a request from @MonicaBrandeis. But it's not working well right now, as you mentioned. Basically the problem is that the aspect ratio of the map is variable and doesn't match the bounds of the city. For now, I've commented out those lines. If we can match the aspect ratio then we can put those back in. I'm not sure if/when I'll have time to do that.

3. Nice catch -- this should be fixed now.

**Comment by MonicaBrandeis** [comment]
The Weight Error Rate by is not defaulting to None on clicking next city? Can you elaborate on this? @sayas01

**Comment by nachtm** [comment]
@MonicaBrandeis say you're looking at MN and you click the radio button to weight by population. Then, if you click the arrow to go to the next city, the map will display weighted by population.

Arguably, if someone selects weight by population, then they want to look at other cities weighted by population as well, so I don't think this is a big issue.

**Comment by MonicaBrandeis** [comment]
Got it, not a blocker, I did not even realize I have that option. I think we are good there and can expecting that is an issue once there is some reporting there!

**Pull request merged**
